begin;

-- ArchitectureIQ feedback is stored one event per row.  Flexible analytics
-- context stays in JSONB while the fields used for idempotency and reporting
-- remain typed and indexed.
create table public.feedback_events (
    event_id text primary key,
    schema_version text not null,
    trace_id text not null,
    trace_created_at timestamptz not null,
    session_id text not null,
    question_id text not null,
    question_version text not null,
    event_type text not null,
    occurred_at timestamptz not null,
    sequence integer not null,
    payload jsonb not null,
    ingest_request_id uuid not null,
    received_at timestamptz not null default now(),

    constraint feedback_events_schema_version_check
        check (schema_version = '1.0'),
    constraint feedback_events_event_type_check
        check (
            event_type in (
                'answer_submitted',
                'custom_setting_proposed',
                'custom_setting_rejected',
                'custom_run_completed',
                'custom_run_failed',
                'comment_submitted'
            )
        ),
    constraint feedback_events_sequence_check check (sequence > 0),
    constraint feedback_events_payload_object_check
        check (jsonb_typeof(payload) = 'object'),
    constraint feedback_events_event_id_check
        check (
            event_id = btrim(event_id)
            and length(event_id) between 1 and 200
            and event_id !~ E'[\r\n]'
        ),
    constraint feedback_events_trace_id_check
        check (
            trace_id = btrim(trace_id)
            and length(trace_id) between 1 and 200
            and trace_id !~ E'[\r\n]'
        ),
    constraint feedback_events_session_id_check
        check (
            session_id = btrim(session_id)
            and length(session_id) between 1 and 200
            and session_id !~ E'[\r\n]'
        ),
    constraint feedback_events_question_id_check
        check (
            question_id = btrim(question_id)
            and length(question_id) between 1 and 200
            and question_id !~ E'[\r\n]'
        ),
    constraint feedback_events_question_version_check
        check (
            question_version = btrim(question_version)
            and length(question_version) between 1 and 200
            and question_version !~ E'[\r\n]'
        )
);

comment on table public.feedback_events is
    'Append-only ArchitectureIQ feedback event store. event_id is the idempotency key.';
comment on column public.feedback_events.payload is
    'Validated event payload, including optional attempt/release/family/question-type analytics context.';
comment on column public.feedback_events.ingest_request_id is
    'Non-secret correlation id generated by feedback-ingest.';

-- These indexes cover the primary Kahoot-style reporting dimensions.
create index feedback_events_session_time_idx
    on public.feedback_events (session_id, occurred_at desc);
create index feedback_events_question_time_idx
    on public.feedback_events (question_id, occurred_at desc);
create index feedback_events_type_time_idx
    on public.feedback_events (event_type, occurred_at desc);
create index feedback_events_occurred_at_idx
    on public.feedback_events (occurred_at desc);
create index feedback_events_attempt_time_idx
    on public.feedback_events (
        (nullif(payload ->> 'attempt_id', '')),
        occurred_at desc
    );
create index feedback_events_release_time_idx
    on public.feedback_events (
        (nullif(payload ->> 'release_id', '')),
        occurred_at desc
    );
create index feedback_events_family_question_type_idx
    on public.feedback_events (
        (nullif(payload ->> 'family', '')),
        (nullif(payload ->> 'question_type', ''))
    );

-- RLS has no anon/authenticated policies.  The Edge Function writes with the
-- service role, which bypasses RLS, and no browser/client receives that key.
alter table public.feedback_events enable row level security;
alter table public.feedback_events force row level security;

revoke all on table public.feedback_events from public, anon, authenticated;
grant select, insert on table public.feedback_events to service_role;

-- Defence in depth: even privileged application code cannot rewrite history.
-- Schema owners can deliberately remove/disable this trigger in a migration.
create function public.reject_feedback_event_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    raise exception using
        errcode = '55000',
        message = 'feedback_events is append-only';
end;
$$;

revoke all on function public.reject_feedback_event_mutation()
    from public, anon, authenticated;

create trigger feedback_events_append_only
before update or delete or truncate on public.feedback_events
for each statement execute function public.reject_feedback_event_mutation();

-- REPORT-001 starting views.  security_invoker keeps the underlying table's
-- RLS and grants in force; explicit revokes avoid accidental API exposure.
create view public.feedback_session_summary
with (security_invoker = true, security_barrier = true)
as
select
    session_id,
    nullif(payload ->> 'attempt_id', '') as attempt_id,
    min(occurred_at) as started_at,
    max(occurred_at) as last_event_at,
    min(received_at) as first_received_at,
    max(received_at) as last_received_at,
    array_remove(
        array_agg(distinct nullif(payload ->> 'release_id', '')),
        null
    ) as release_ids,
    array_remove(
        array_agg(distinct nullif(payload ->> 'family', '')),
        null
    ) as families,
    array_remove(
        array_agg(distinct nullif(payload ->> 'question_type', '')),
        null
    ) as question_types,
    count(*) as event_count,
    count(distinct question_id) as question_count,
    count(*) filter (where event_type = 'answer_submitted') as answer_count,
    count(*) filter (
        where event_type = 'answer_submitted'
          and payload -> 'is_correct' = 'true'::jsonb
    ) as correct_answer_count,
    round(
        count(*) filter (
            where event_type = 'answer_submitted'
              and payload -> 'is_correct' = 'true'::jsonb
        )::numeric
        / nullif(
            count(*) filter (where event_type = 'answer_submitted'),
            0
        ),
        4
    ) as accuracy,
    count(*) filter (
        where event_type = 'custom_setting_proposed'
    ) as proposal_count,
    count(*) filter (
        where event_type = 'custom_setting_rejected'
    ) as rejected_setting_count,
    count(*) filter (
        where event_type = 'custom_run_completed'
    ) as completed_run_count,
    count(*) filter (
        where event_type = 'custom_run_failed'
    ) as failed_run_count,
    count(*) filter (where event_type = 'comment_submitted') as comment_count
from public.feedback_events
group by session_id, nullif(payload ->> 'attempt_id', '');

create view public.feedback_question_stats
with (security_invoker = true, security_barrier = true)
as
select
    question_id,
    question_version,
    nullif(payload ->> 'release_id', '') as release_id,
    nullif(payload ->> 'family', '') as family,
    nullif(payload ->> 'dataset_id', '') as dataset_id,
    nullif(payload ->> 'question_type', '') as question_type,
    min(occurred_at) as first_event_at,
    max(occurred_at) as last_event_at,
    count(distinct session_id) as session_count,
    count(distinct nullif(payload ->> 'attempt_id', '')) as attempt_count,
    count(*) filter (where event_type = 'answer_submitted') as answer_count,
    count(*) filter (
        where event_type = 'answer_submitted'
          and payload -> 'is_correct' = 'true'::jsonb
    ) as correct_answer_count,
    round(
        count(*) filter (
            where event_type = 'answer_submitted'
              and payload -> 'is_correct' = 'true'::jsonb
        )::numeric
        / nullif(
            count(*) filter (where event_type = 'answer_submitted'),
            0
        ),
        4
    ) as accuracy,
    count(*) filter (
        where event_type = 'custom_setting_proposed'
    ) as proposal_count,
    count(*) filter (
        where event_type = 'custom_setting_rejected'
    ) as rejected_setting_count,
    count(*) filter (
        where event_type = 'custom_run_completed'
    ) as completed_run_count,
    count(*) filter (
        where event_type = 'custom_run_failed'
    ) as failed_run_count,
    count(*) filter (where event_type = 'comment_submitted') as comment_count
from public.feedback_events
group by
    question_id,
    question_version,
    nullif(payload ->> 'release_id', ''),
    nullif(payload ->> 'family', ''),
    nullif(payload ->> 'dataset_id', ''),
    nullif(payload ->> 'question_type', '');

create view public.feedback_comments
with (security_invoker = true, security_barrier = true)
as
select
    event_id,
    occurred_at,
    received_at,
    session_id,
    nullif(payload ->> 'attempt_id', '') as attempt_id,
    question_id,
    question_version,
    nullif(payload ->> 'release_id', '') as release_id,
    nullif(payload ->> 'family', '') as family,
    nullif(payload ->> 'question_type', '') as question_type,
    payload ->> 'category' as category,
    payload ->> 'text' as comment_text
from public.feedback_events
where event_type = 'comment_submitted';

create view public.feedback_proposals
with (security_invoker = true, security_barrier = true)
as
select
    event_id,
    occurred_at,
    received_at,
    session_id,
    nullif(payload ->> 'attempt_id', '') as attempt_id,
    question_id,
    question_version,
    nullif(payload ->> 'release_id', '') as release_id,
    nullif(payload ->> 'family', '') as family,
    nullif(payload ->> 'question_type', '') as question_type,
    case event_type
        when 'custom_setting_proposed' then 'proposed'
        when 'custom_setting_rejected' then 'rejected'
    end as setting_status,
    payload ->> 'label' as label,
    payload -> 'setting' as setting,
    payload -> 'inherited_from' as inherited_from,
    case
        when jsonb_typeof(payload -> 'n_seeds') = 'number'
        then (payload ->> 'n_seeds')::integer
        else null
    end as n_seeds,
    case
        when jsonb_typeof(payload -> 'base_seed') = 'number'
        then (payload ->> 'base_seed')::integer
        else null
    end as base_seed
from public.feedback_events
where event_type in ('custom_setting_proposed', 'custom_setting_rejected');

revoke all on table
    public.feedback_session_summary,
    public.feedback_question_stats,
    public.feedback_comments,
    public.feedback_proposals
from public, anon, authenticated;

grant select on table
    public.feedback_session_summary,
    public.feedback_question_stats,
    public.feedback_comments,
    public.feedback_proposals
to service_role;

comment on view public.feedback_session_summary is
    'REPORT-001 starting point: one row per session and attempt.';
comment on view public.feedback_question_stats is
    'REPORT-001 starting point: Kahoot-style per-question attempts and accuracy.';
comment on view public.feedback_comments is
    'REPORT-001 starting point: categorized per-question comments.';
comment on view public.feedback_proposals is
    'REPORT-001 starting point: proposed and client-rejected custom settings.';

commit;
